default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost
  username: school
  password: XyrQjqva9ZAueFh3nQWdMGZBmTieBJiv

development:
  <<: *default
  database: school_eaeh

test:
  <<: *default
  database: school_eaeh

production:
  <<: *default
  database: school_eaeh
